sudo: required
language: php

services:
  - docker

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

install:
  - composer install

script:
  - php vendor/bin/phpunit -v
  - tests/resources/run_functional_tests.sh
